version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gym_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gym_db
      MYSQL_USER: gymuser
      MYSQL_PASSWORD: gympassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - gym_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: .
    container_name: gym_backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: gym_db
      JWT_SECRET: xxxx
      JWT_EXPIRATION_HOURS: 24
      SERVER_PORT: 8080
      GIN_MODE: release
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gym_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  gym_network:
    driver: bridge

